# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d477bef836504b9a09908eaff8ced9af59b16e241609892779b9e7b28552f3f913322a83002257702f7f75f5c1b7a83815514e297de38b54fc3a81af4d2875

test:
  secret_key_base: 764553474ae6fd4559834feb8dc4c23adb4b42472faeffeee6d5e48e54231a3e5b9842ff14a239da41b559aec5092efe8178d6f40f310668458ee8f5d0578a25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
